### PR TITLE
Only print string if process was running in the first place.

### PR DESCRIPTION
**Pull request by netzbasis**
If it's not obvious i like this little tool. Great idea.

I'm unsure if this is better than the default behavior but for what I have in mind I'd like to know if the process was running or not in the first place.

### CODE REVIEW

**Comment by e-zk** [comment]
honestly this is a great idea. will merge.

**Comment by netzbasis** [comment]
Thanks.

Still testing stuff. Here another example. It's a little clunky with scripting languages.
after -n perl -e "pkg_add - update done" | xmessage -file -

**Comment by e-zk** [comment]
in the case that the program wasn't running at all, do you think would be wiser to print that "process not in process list." message to stderr regardless of whether the user wants verbosity via `-v`?  

I say this because if the `-e string` isn't printed it would be little strange if there is no indication of why the string hasn't been printed.

**Comment by netzbasis** [comment]
Sure, good idea. Can you edit the commit, or do another one after the fact. To print the "process not in process list." message to stderr regardless of whether the user wants verbosity.

**Comment by e-zk** [comment]
yeah, gotcha. thanks for the pledge-ing as well!

**Pull request merged**
